language: node_js
node_js:
  - "node"
dist: trusty
branches:
  only:
    - master
env:
  - TEST_SUITE=test-security
  - TEST_SUITE=test-index
  - TEST_SUITE=test-integration
script:
  - npm run $TEST_SUITE
